### ISSUE TITLE
more.html typo

### ISSUE THREAD

**Issue by aaronforge** [fatejin/kakao-clone-v2#2]
You have a typo on the [31st line in more.html](https://github.com/fatejin/kakao-clone-v2/blob/master/more.html#L31).

It's not "settings.html" in anchor tag, but "setting.html".

**Comment by fatejin** [comment]
> You have a typo on the [31st line in more.html](https://github.com/fatejin/kakao-clone-v2/blob/master/more.html#L31).
> 
> It's not "settings.html" in anchor tag, but "setting.html".

Thank you for advising about that. I really appreciate it. It came out just small stuffs from error. Ahh..  My feeling is so empty now. If you don't mind, Let's keep in touch. Me too. I wanna be full stack developer.

**Comment by aaronforge** [comment]
My pleasure. We can keep in touch on Slack or GitHub or whatever you want.

**Comment by aaronforge** [comment]
I think you might be able to resolve this issue.
I'm closing this.

**Comment by fatejin** [comment]
> I think you might be able to resolve this issue.
> I'm closing this.
Sure,  keep in touch. After part time job, I have to see, but I know what problem is on there. Enjoy your weekend.

**Comment by aaronforge** [comment]
> I think you might be able to resolve this issue.
> I'm closing this.
> Sure, keep in touch. After part time job, I have to see, but I know what problem is on there. Enjoy your weekend.

Thanks, you too!
